### ISSUE TITLE
pubDate broken

### ISSUE THREAD

**Issue by dfeinzimer** [kernelpop/beepboopbackend#12]
In `api/bff.py` -> In the summary feed `pubDate` is not working.

pubDate = datetime.datetime.strptime(x['article_date'], "%m/%d/%Y").strftime("%a, %d %b %Y%H:%M:%S %Z")`

**Comment by yroush** [comment]
All date fields in the database should be in format MM/DD/YYYY.

in python, the %Y refers to the year in YYYY format.  

Fixed and will push changes to database fill script.
