### ISSUE TITLE
Delete tag not working

### ISSUE THREAD

**Issue by dfeinzimer** [kernelpop/beepboopbackend#8]
I tried to delete the following tag with 
`localhost/tags/2/articles=1`

and received error:
`{
    "message": "Not Found: http://tags_services/tags/2/articles%3D1",
    "status": 404
}`

I also believe there may be an error in the documentation here: https://github.com/kernelpop/beepboopbackend/wiki/API-Usage:-Tags#delete-tag

**Comment by yroush** [comment]
Changed the api and updated the documentation so it more accurately explains how to delete.
