### ISSUE TITLE
Get URLs by tag not working

### ISSUE THREAD

**Issue by dfeinzimer** [kernelpop/beepboopbackend#9]
Tried
`localhost/tags/tag/1`
`localhost/tags/tag/tags=1`
`localhost/tags/tag/articles/1` (even though that doesn't make sense)
`localhost/tags/tag/articles/tags/1`

None worked

Documentation could also be improved here:
https://github.com/kernelpop/beepboopbackend/wiki/API-Usage:-Tags#get-urls-by-tag

**Comment by yroush** [comment]
Updated the documentation to show how to properly use the api.
